fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black app
        pass_filenames: false
        language: system
        args: [--config=pyproject.toml]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort app
        pass_filenames: false
        language: system
        args: [--settings-path=pyproject.toml]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint app
        pass_filenames: false
        language: system
        args: [--rcfile=.pylintrc]